# Generated by Django 5.0 on 2024-03-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('incorporation_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('cours_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=255)),
                ('lesson_num', models.IntegerField()),
                ('lesson_content', models.TextField()),
                ('lesson_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('podcast_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('content', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(null=True)),
                ('question_type', models.CharField(max_length=255)),
                ('question_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('name_sector', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('picture_url', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswersQuizes',
            fields=[
                ('answer_quizes_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=255)),
                ('answer_points', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.questions')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsLesson',
            fields=[
                ('question_lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255)),
                ('answer', models.BooleanField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('quize_id', models.AutoField(primary_key=True, serialize=False)),
                ('quize_name', models.CharField(max_length=255)),
                ('quize_theme', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
                ('section_num', models.IntegerField()),
                ('section_description', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.courses')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.sections'),
        ),
        migrations.CreateModel(
            name='SectorCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.company')),
                ('name_sector', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backendapp.sectors')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id_investment', models.AutoField(primary_key=True, serialize=False)),
                ('valuation', models.IntegerField()),
                ('equity_offered', models.IntegerField()),
                ('pitch', models.TextField(blank=True)),
                ('share_price', models.IntegerField()),
                ('tax_relief', models.IntegerField()),
                ('num_investors', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.type')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(to='backendapp.articles')),
                ('podcasts', models.ManyToManyField(to='backendapp.podcasts')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracks_completed', models.IntegerField()),
                ('courses_completed', models.IntegerField()),
                ('projects_completed', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('daily_exp', models.IntegerField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.podcasts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('project_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.utilisateurs')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.utilisateurs')),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('checkpoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_done', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.lessons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.utilisateurs')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
